version: '2'

networks:
    fabric:

services:

    orderer.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer.example.com
        environment:
            - ORDERER_HOST=orderer.example.com
        extra_hosts:
            - "peer0.as1.example.com:${AS1_IP}"
            - "peer0.as2.example.com:${AS2_IP}"
        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/tls
            - ../channel-artifacts/:/var/hyperledger/configs
            - ../persistence/orderer/:/var/hyperledger/production
        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7050:7050