---
- name: Set basic configurations for a new BGPcommunities Hyperledger configuration
  hosts: ASservers
  remote_user: ubuntu
  become: true
  roles:
    - {role: geerlingguy.nodejs}
    - {role: geerlingguy.docker}
    - {role: geerlingguy.git}
    - {role: gantsign.golang,  golang_gopath: '$HOME/go_projects'} 
